### ISSUE TITLE
Removing an Object from a Shoebox Store with .remove() does not propagate the changes back to the view

### ISSUE THREAD

**Issue by sanity** [kwebio/shoebox#6]
Reported by @rpanic

**Comment by sanity** [comment]
This way the render or renderEach does not update the data

**Comment by sanity** [comment]
This issue is more likely in `renderEach` in Kweb, as deletion from a view is [fairly well unit tested](https://github.com/kwebio/shoebox/blob/master/src/test/kotlin/io/kweb/shoebox/ViewSpec.kt#L92) in Shoebox.

**Comment by rpanic** [comment]
After changing a bit of my code, i noticed that removing with .remove() works again. Since I don´t know what change exactly caused it to work again, i can´t replicate it anymore. I would suspect that I there was something wrong with my particular data, but I can´t say for sure.

**Comment by sanity** [comment]
Ok, I'm going to work on beefing up the unit tests around this stuff, and will close this issue for now.
